### PR TITLE
Applied patches needed after changes to the drm code in rc5.

### PR DESCRIPTION
**Pull request by winsock**
Most likely you have pulled these patches already, however there were two changes I still needed after applying these patches. It is possible I just missed a patch that contains the change. I have no clue if this breaks etiquette for making a PR on github out of already submitted patches, if so just ignore.
Since tegra-nouveau-rootfs points to this branch, if someone(like me) used a different linux repo(linux-next.git) they would be unable to build a rootfs with nouveau using your script.
http://patchwork.freedesktop.org/series/709/
https://patchwork.freedesktop.org/patch/67153/

### CODE REVIEW

**Comment by Gnurou** [comment]
Problem with this is that tegra-nouveau-rootfs would not compile anymore. If you need to use a different kernel, can you carry that patch yourself?

**Comment by winsock** [comment]
True, it would break for the old kernel that the repo xml still points at. Yeah, I can carry the patch myself. I don't "need" to use linux-next upstream. I just gave myself a challenge of getting the Shield Tablet running mainline + nouveau since it supports gk20a now.
I'll go ahead and close this :)

**Comment by Gnurou** [comment]
Oh, great - I'd love to see Shield Tablet using mainline and Nouveau, and yes it is a quite realistic goal. Don't hesitate to open issues here if you need help.

**Comment by Gnurou** [comment]
Or maybe you will want to open issues on the tegra-nouveau-rootfs project, as your work would allow us to add Shield Tablet as a supported target.

**Comment by winsock** [comment]
I think I will do that, I'm going back through my device tree source files at the moment since my frame buffer isn't working at the moment. But the kernel seems to be running fine, since the tab doesn't reboot!

**Comment by Gnurou** [comment]
Check out https://github.com/Gnurou/linux/tree/st8 - it's very out-of-date, but it boots with the display on (using simple-framebuffer, not a real DRM driver) and may be useful to get feedback from the device.

**Pull request closed without merging**
